export enum Obcine {
	Maribor = 'Maribor',
	Benedikt = 'Benedikt',
	Cerkvenjak = 'Cervenjak',
	Duplek = 'Duplek',
	HoceSlivnica = 'Hoče-Slivnica',
	Kungota = 'Kungota',
	Lenart = 'Lenart',
	LovrencNaPohorju = 'Lovrenc na Pohorju',
	MiklavzNaDravskemPolju = 'Miklavž na Dravskem polju',
	Pesnica = 'Pesnica',
	RaceFram = 'Rače-Fram',
	Ruse = 'Ruše',
	SelnicaObDravi = 'Selnica ob Dravi',
	Starse = 'Starše',
	SvetaTrojica = 'Sveta Trojica',
	SvetaAna = 'Sveta Ana',
	SvetiJurijVSlovenskihGoricah = 'Sveti Jurij v Slovenskih goricah',
	Sentilj = 'Šentilj'
}
